#trigger:
#- main

pool:
  vmImage: ubuntu-latest
  
variables:
  buildCOnfiguration: 'Release'
  webRepository: 'web'
  tag: '$(Build.BuildID)'

stages:
  - stage: 'Build'
    displayName: 'Build and push'
    jobs:
      - job: 'Build'
        displayName: 'Build job'
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Container Registry Connection'
            repository: '$(webRepository)'
            command: 'buildAndPush'
            Dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
            tags: '$(tag)'
            
  - stage: 'Deploy'
    displayName: 'Deploy the container'
    dependsOn: Build
    jobs:
      - job: 'Deploy'
        displayName: 'Deploy job'
        pool:
          vmImage: 'ubuntu-20.04'
        variables:
        - group: Release
        steps:
        - task: AzureWebAppContainer@1
          inputs:
           appName: $(WebAppName)
           azureSubscription: 'Resource Manager - Tailspin - Space Game'
           imageName: $(RegistryName)/$(webRepository):$(build.buildId)